### model
model_name_or_path: /public/data0/NLP/users/tanwentao1/52/project/LLaMA-Factory/saves/qwen2_vl-7b/full/iter1

### method
stage: dpo
do_train: true
finetuning_type: full
pref_beta: 0.1
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]
deepspeed: examples/deepspeed/ds_z3_config.json
# pref_ftx: 0.5

### dataset
dataset: my_qwen2vl_dpo
template: qwen2_vl
cutoff_len: 4096
# max_samples: 8000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/qwen2_vl-7b/full/iter2
logging_steps: 1
save_steps: 5000000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 2.0e-6
num_train_epochs: 1.0
weight_decay: 0. 
warmup_steps: 0 
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
